# -*- coding: utf-8 -*-
"""v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Syxqqfg2jokbz01O3lMovIAfd0gMcZwr

# STAT 425 Final Project


Group 5

Rebecca Li & Ning Mu

Goal: Train a customized embedding model using SciBERT and Houslby adapter for automotive diagnostics.

The training will involve a contrastive loss function and the performance will be evaluated using top-5 recall.

# Setup
"""

import pandas as pd
import json

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/MyDrive/STAT 425/automotive_faults_aktc_obike_et_al.json')as f:
  df = json.load(f)

"""## Analyze Data Structure



"""

first_entry = df[0]

print(f"Type of symptoms field: {type(first_entry['symptoms'])}")
if isinstance(first_entry['symptoms'], list):
    print(f"Number of symptoms: {len(first_entry['symptoms'])}")
    if first_entry['symptoms']:
        print(f"Type of first symptom: {type(first_entry['symptoms'][0])}")
        print(f"Example first symptom: '{first_entry['symptoms'][0]}'")

print("\n--- Analysis of 'diagnosis_steps' field ---")
print(f"Type of diagnosis_steps field: {type(first_entry['diagnosis_steps'])}")
if isinstance(first_entry['diagnosis_steps'], list):
    print(f"Number of diagnosis steps: {len(first_entry['diagnosis_steps'])}")
    if first_entry['diagnosis_steps']:
        print(f"Type of first diagnosis step entry: {type(first_entry['diagnosis_steps'][0])}")
        if isinstance(first_entry['diagnosis_steps'][0], dict):
            print(f"Keys in first diagnosis step entry: {first_entry['diagnosis_steps'][0].keys()}")
            print(f"Type of 'step' in first diagnosis step: {type(first_entry['diagnosis_steps'][0]['step'])}")
            print(f"Example 'step': '{first_entry['diagnosis_steps'][0]['step']}'")
            print(f"Type of 'result' in first diagnosis step: {type(first_entry['diagnosis_steps'][0]['result'])}")
            if isinstance(first_entry['diagnosis_steps'][0]['result'], list):
                print(f"Number of results in first diagnosis step: {len(first_entry['diagnosis_steps'][0]['result'])}")
                if first_entry['diagnosis_steps'][0]['result']:
                    print(f"Type of first result in first diagnosis step: {type(first_entry['diagnosis_steps'][0]['result'][0])}")
                    print(f"Example first result: '{first_entry['diagnosis_steps'][0]['result'][0]}'")

"""## Data Preprocessing and Splitting


Split the dataset into training, evaluation, and testing sets with an 80/10/10 ratio.

"""

data_pairs = []

for entry in df:
    symptoms = entry.get('symptoms', [])
    diagnosis_steps = entry.get('diagnosis_steps', [])

    for symptom_text in symptoms:
        for diagnosis_step_dict in diagnosis_steps:
            step_text = diagnosis_step_dict.get('step', '')
            if symptom_text and step_text:
                data_pairs.append((symptom_text, step_text))

print(f"Total number of symptom-diagnosis pairs created: {len(data_pairs)}")

from sklearn.model_selection import train_test_split

train_data, temp_data = train_test_split(data_pairs, test_size=0.2, random_state=42)

val_data, test_data = train_test_split(temp_data, test_size=0.5, random_state=42)

print(f"Training set size: {len(train_data)}")
print(f"Validation set size: {len(val_data)}")
print(f"Test set size: {len(test_data)}")

"""# `model_1`: SciBERT and Houslby Adapter


Houslby adapter architecture  (https://github.com/google-research/adapter-bert/tree/master)

 Configure the model to freeze the SciBERT base model weights and only allow training for the adapter layers and layer normalization parameters.

"""

!pip install adapters
import adapters

from adapters import AdapterConfig, AutoAdapterModel
from transformers import AutoTokenizer

model_name = "allenai/scibert_scivocab_uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)
scibert_model = AutoAdapterModel.from_pretrained(model_name)

# 1. Define Houslby adapter configuration
adapter_config = AdapterConfig.load(
    "houlsby",
    reduction_factor=8,
    non_linearity="gelu"
)

# 2. Add the adapter to the SciBERT model
# The arguments are correct for adapter-transformers's add_adapter: (adapter_name, config_object)
scibert_model.add_adapter("houslby_adapter", adapter_config)

# 3. Set 'houslby_adapter' as the active adapter
scibert_model.set_active_adapters("houslby_adapter")

# 4. Freeze all parameters of the scibert_model
for param in scibert_model.parameters():
    param.requires_grad = False

# 5. Unfreeze the parameters of the active adapter and the layer normalization layers
scibert_model.train_adapter("houslby_adapter")

trainable_params = [n for n, p in scibert_model.named_parameters() if p.requires_grad]
print(f"\nNumber of trainable parameters: {len(trainable_params)}")
print("Trainable parameters example:")
for i, name in enumerate(trainable_params[:5]): # Print first 5 trainable params
    print(name)
if len(trainable_params) > 5:
    print("...")

import torch
from torch.utils.data import Dataset, DataLoader

class SymptomDiagnosisDataset(Dataset):
    def __init__(self, data_pairs, tokenizer, max_length=128):
        self.data_pairs = data_pairs
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data_pairs)

    def __getitem__(self, idx):
        symptom, diagnosis_step = self.data_pairs[idx]

        # Tokenize symptom
        encoded_symptom = self.tokenizer.encode_plus(
            symptom,
            add_special_tokens=True,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )

        # Tokenize diagnosis step
        encoded_diagnosis_step = self.tokenizer.encode_plus(
            diagnosis_step,
            add_special_tokens=True,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )

        return {
            'symptom_input_ids': encoded_symptom['input_ids'].squeeze(0),
            'symptom_attention_mask': encoded_symptom['attention_mask'].squeeze(0),
            'diagnosis_input_ids': encoded_diagnosis_step['input_ids'].squeeze(0),
            'diagnosis_attention_mask': encoded_diagnosis_step['attention_mask'].squeeze(0)
        }

# Create dataset instances
train_dataset = SymptomDiagnosisDataset(train_data, tokenizer)
val_dataset = SymptomDiagnosisDataset(val_data, tokenizer)
test_dataset = SymptomDiagnosisDataset(test_data, tokenizer)

# Define batch size
batch_size = 32

# Create DataLoader instances
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print(f"Number of training batches: {len(train_dataloader)}")
print(f"Number of validation batches: {len(val_dataloader)}")
print(f"Number of test batches: {len(test_dataloader)}")

"""## Training Loop


"""

import torch
from sentence_transformers import SentenceTransformer, models, losses

# Define a custom module that wraps our AutoAdapterModel
# This is necessary because models.Transformer does not accept a pre-loaded model instance
# directly via the 'model' keyword in the current sentence_transformers version.
class AdapterSentenceTransformerModule(torch.nn.Module):
    def __init__(self, hf_model, hf_tokenizer, max_seq_length):
        super().__init__()
        self.auto_model = hf_model
        self.tokenizer = hf_tokenizer
        self.max_seq_length = max_seq_length
        self.word_embedding_dimension = hf_model.config.hidden_size # Get dimension from model config

    def forward(self, features):
        # Extract input_ids and attention_mask from the features dictionary
        input_ids = features['input_ids']
        attention_mask = features['attention_mask']

        # Pass through the underlying AutoAdapterModel
        output = self.auto_model(input_ids=input_ids, attention_mask=attention_mask, return_dict=True)

        # Update features dictionary as expected by subsequent modules (e.g., Pooling)
        # 'token_embeddings' are the last hidden states
        features.update({'token_embeddings': output.last_hidden_state, 'attention_mask': attention_mask})

        # If the model provides a pooler_output (e.g., from CLS token), include it.
        if hasattr(output, 'pooler_output') and output.pooler_output is not None:
            features['cls_token_embeddings'] = output.pooler_output

        return features

    def save(self, path):
        # Save the underlying AutoAdapterModel
        self.auto_model.save_pretrained(path)
        # Save the tokenizer
        self.tokenizer.save_pretrained(path)

# Create an instance of our custom transformer module, using the already configured scibert_model and tokenizer
custom_transformer_module = AdapterSentenceTransformerModule(scibert_model, tokenizer, max_seq_length=128)

# Create the pooling layer. Mean pooling is standard for BERT-like models for sentence embeddings.
pooling_model = models.Pooling(custom_transformer_module.word_embedding_dimension, pooling_mode='mean')

# Combine into a SentenceTransformer model
# Removed 'tokenizer' and 'max_seq_length' as direct arguments to SentenceTransformer
embedding_model = SentenceTransformer(modules=[custom_transformer_module, pooling_model])

# Define the contrastive loss function
# MultipleNegativesRankingLoss takes the SentenceTransformer model directly.
loss_fn = losses.MultipleNegativesRankingLoss(model=embedding_model)

import torch
import torch.optim as optim

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
embedding_model.to(device)
print(f"Model moved to device: {device}")

# 1. Initialize an optimizer for the embedding_model
# Only trainable parameters (adapter and layer norm) will be passed due to scibert_model.train_adapter setting
optimizer = optim.AdamW(embedding_model.parameters(), lr=2e-5)

# 2. Define the number of training epochs
num_epochs = 3

# Training loop
for epoch in range(num_epochs):
    print(f"\n--- Epoch {epoch+1}/{num_epochs} ---")
    embedding_model.train() # Set model to training mode
    total_train_loss = 0

    for step, batch in enumerate(train_dataloader):
        optimizer.zero_grad() # Clear gradients

        # Move batch tensors to the appropriate device
        symptom_input_ids = batch['symptom_input_ids'].to(device)
        symptom_attention_mask = batch['symptom_attention_mask'].to(device)
        diagnosis_input_ids = batch['diagnosis_input_ids'].to(device)
        diagnosis_attention_mask = batch['diagnosis_attention_mask'].to(device)

        # Prepare sentence_features for the MultipleNegativesRankingLoss
        # The loss function will internally call embedding_model on these features
        sentence_features_symptoms = {'input_ids': symptom_input_ids, 'attention_mask': symptom_attention_mask}
        sentence_features_diagnosis = {'input_ids': diagnosis_input_ids, 'attention_mask': diagnosis_attention_mask}

        # For MultipleNegativesRankingLoss, if input is [query_features, positive_features],
        # and query_i is positive with positive_i, labels should be torch.arange(batch_size)
        labels = torch.arange(len(symptom_input_ids), dtype=torch.long, device=device)

        # Compute loss
        loss = loss_fn([sentence_features_symptoms, sentence_features_diagnosis], labels)

        loss.backward() # Perform backpropagation
        optimizer.step() # Update model parameters

        total_train_loss += loss.item()

        if (step + 1) % 10 == 0: # Print loss every 10 steps for progress monitoring
            print(f"  Step {step+1}/{len(train_dataloader)}, Training Loss: {loss.item():.4f}")

    avg_train_loss = total_train_loss / len(train_dataloader)
    print(f"Epoch {epoch+1} Training Loss: {avg_train_loss:.4f}")

    # Validation loop
    embedding_model.eval() # Set model to evaluation mode
    total_val_loss = 0
    with torch.no_grad(): # Disable gradient calculations for validation
        for batch in val_dataloader:
            symptom_input_ids = batch['symptom_input_ids'].to(device)
            symptom_attention_mask = batch['symptom_attention_mask'].to(device)
            diagnosis_input_ids = batch['diagnosis_input_ids'].to(device)
            diagnosis_attention_mask = batch['diagnosis_attention_mask'].to(device)

            sentence_features_symptoms = {'input_ids': symptom_input_ids, 'attention_mask': symptom_attention_mask}
            sentence_features_diagnosis = {'input_ids': diagnosis_input_ids, 'attention_mask': diagnosis_attention_mask}

            labels = torch.arange(len(symptom_input_ids), dtype=torch.long, device=device)

            val_loss = loss_fn([sentence_features_symptoms, sentence_features_diagnosis], labels)
            total_val_loss += val_loss.item()

    avg_val_loss = total_val_loss / len(val_dataloader)
    print(f"Epoch {epoch+1} Validation Loss: {avg_val_loss:.4f}")

# 5. Save the trained embedding_model
output_model_path = "./fine_tuned_scibert_adapter_model"
embedding_model.save(output_model_path)
print(f"\nModel saved to {output_model_path}")

import torch
import torch.optim as optim

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
embedding_model.to(device)
print(f"Model moved to device: {device}")

# 1. Initialize an optimizer for the embedding_model
# Only trainable parameters (adapter and layer norm) will be passed due to scibert_model.train_adapter setting
optimizer = optim.AdamW(embedding_model.parameters(), lr=2e-5)

# 2. Define the number of training epochs
num_epochs = 60 # Can be adjusted based on performance

# Training loop
for epoch in range(num_epochs):
    print(f"\n--- Epoch {epoch+1}/{num_epochs} ---")
    embedding_model.train() # Set model to training mode
    total_train_loss = 0

    for step, batch in enumerate(train_dataloader):
        optimizer.zero_grad() # Clear gradients

        # Move batch tensors to the appropriate device
        symptom_input_ids = batch['symptom_input_ids'].to(device)
        symptom_attention_mask = batch['symptom_attention_mask'].to(device)
        diagnosis_input_ids = batch['diagnosis_input_ids'].to(device)
        diagnosis_attention_mask = batch['diagnosis_attention_mask'].to(device)

        # Prepare sentence_features for the MultipleNegativesRankingLoss
        # The loss function will internally call embedding_model on these features
        sentence_features_symptoms = {'input_ids': symptom_input_ids, 'attention_mask': symptom_attention_mask}
        sentence_features_diagnosis = {'input_ids': diagnosis_input_ids, 'attention_mask': diagnosis_attention_mask}

        # For MultipleNegativesRankingLoss, if input is [query_features, positive_features],
        # and query_i is positive with positive_i, labels should be torch.arange(batch_size)
        labels = torch.arange(len(symptom_input_ids), dtype=torch.long, device=device)

        # Compute loss
        loss = loss_fn([sentence_features_symptoms, sentence_features_diagnosis], labels)

        loss.backward() # Perform backpropagation
        optimizer.step() # Update model parameters

        total_train_loss += loss.item()

        if (step + 1) % 10 == 0: # Print loss every 10 steps for progress monitoring
            print(f"  Step {step+1}/{len(train_dataloader)}, Training Loss: {loss.item():.4f}")

    avg_train_loss = total_train_loss / len(train_dataloader)
    print(f"Epoch {epoch+1} Training Loss: {avg_train_loss:.4f}")

    # Validation loop
    embedding_model.eval() # Set model to evaluation mode
    total_val_loss = 0
    with torch.no_grad(): # Disable gradient calculations for validation
        for batch in val_dataloader:
            symptom_input_ids = batch['symptom_input_ids'].to(device)
            symptom_attention_mask = batch['symptom_attention_mask'].to(device)
            diagnosis_input_ids = batch['diagnosis_input_ids'].to(device)
            diagnosis_attention_mask = batch['diagnosis_attention_mask'].to(device)

            sentence_features_symptoms = {'input_ids': symptom_input_ids, 'attention_mask': symptom_attention_mask}
            sentence_features_diagnosis = {'input_ids': diagnosis_input_ids, 'attention_mask': diagnosis_attention_mask}

            labels = torch.arange(len(symptom_input_ids), dtype=torch.long, device=device)

            val_loss = loss_fn([sentence_features_symptoms, sentence_features_diagnosis], labels)
            total_val_loss += val_loss.item()

    avg_val_loss = total_val_loss / len(val_dataloader)
    print(f"Epoch {epoch+1} Validation Loss: {avg_val_loss:.4f}")

# 5. Save the trained embedding_model
output_model_path = "./fine_tuned_scibert_adapter_model"
embedding_model.save(output_model_path)
print(f"\nModel saved to {output_model_path}")

import torch
from sentence_transformers import SentenceTransformer, models, losses

class AdapterSentenceTransformerModule(torch.nn.Module):
    def __init__(self, hf_model, hf_tokenizer, max_seq_length):
        super().__init__()
        self.auto_model = hf_model
        self.tokenizer = hf_tokenizer
        self.max_seq_length = max_seq_length
        self.word_embedding_dimension = hf_model.config.hidden_size

    def forward(self, features):
        # Extract input_ids and attention_mask from the features dictionary
        input_ids = features['input_ids']
        attention_mask = features['attention_mask']

        # Pass through the underlying AutoAdapterModel
        output = self.auto_model(input_ids=input_ids, attention_mask=attention_mask, return_dict=True)

        # 'token_embeddings' are the last hidden states
        features.update({'token_embeddings': output.last_hidden_state, 'attention_mask': attention_mask})

        # If the model provides a pooler_output (e.g., from CLS token), include it.
        if hasattr(output, 'pooler_output') and output.pooler_output is not None:
            features['cls_token_embeddings'] = output.pooler_output

        return features

    def save(self, path):
        self.auto_model.save_pretrained(path)
        self.tokenizer.save_pretrained(path)

    def tokenize(self, texts):
        """
        Tokenizes a list of texts using the underlying tokenizer.
        This method is required for SentenceTransformer to process raw text inputs.
        """
        return self.tokenizer.batch_encode_plus(
            texts,
            add_special_tokens=True,
            padding='max_length',
            truncation=True,
            max_length=self.max_seq_length,
            return_tensors='pt'
        )

# Create an instance of our custom transformer module, using the already configured scibert_model and tokenizer
custom_transformer_module = AdapterSentenceTransformerModule(scibert_model, tokenizer, max_seq_length=128)

# Create the pooling layer. Mean pooling is standard for BERT-like models for sentence embeddings.
pooling_model = models.Pooling(custom_transformer_module.word_embedding_dimension, pooling_mode='mean')

# Combine into a SentenceTransformer model
# Removed 'tokenizer' and 'max_seq_length' as direct arguments to SentenceTransformer
embedding_model = SentenceTransformer(modules=[custom_transformer_module, pooling_model])

# Define the contrastive loss function
# MultipleNegativesRankingLoss takes the SentenceTransformer model directly.
loss_fn = losses.MultipleNegativesRankingLoss(model=embedding_model)

print("Embedding model configured with custom adapter module and contrastive loss defined, including tokenize method.")

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import torch

# Set the model to evaluation mode
embedding_model.eval()

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
embedding_model.to(device)

print("Generating embeddings for the test set...")

# Extract unique symptoms and diagnosis steps from test_data
all_test_symptoms = [pair[0] for pair in test_data]
all_test_diagnosis_steps = [pair[1] for pair in test_data]

unique_test_diagnosis_steps = list(set(all_test_diagnosis_steps))

# Generate embeddings for all unique diagnosis steps (corpus)
print("Generating embeddings for all unique diagnosis steps in the test set...")
corpus_embeddings = embedding_model.encode(
    unique_test_diagnosis_steps,
    batch_size=batch_size,
    show_progress_bar=True,
    convert_to_numpy=True,
    device=device
)

# Generate embeddings for each symptom (query) in the test set and calculate recall and MRR

top_k = 5
hits_at_k = 0
reciprocal_ranks = []
total_queries = 0

print(f"Calculating Top-{top_k} Recall and MRR@{top_k}...")

for i, (symptom, true_diagnosis_step) in enumerate(test_data):
    # Generate embedding for the current symptom (query)
    query_embedding = embedding_model.encode(
        [symptom],
        batch_size=1,
        show_progress_bar=False,
        convert_to_numpy=True,
        device=device
    )[0]

    # Calculate cosine similarity with all unique diagnosis step embeddings
    similarities = cosine_similarity(query_embedding.reshape(1, -1), corpus_embeddings)[0]

    # Get the indices of the most similar diagnosis steps in descending order
    ranked_indices = np.argsort(similarities)[::-1]

    # Calculate Top-K Recall
    top_k_indices = ranked_indices[:top_k]
    retrieved_diagnosis_steps = [unique_test_diagnosis_steps[idx] for idx in top_k_indices]
    if true_diagnosis_step in retrieved_diagnosis_steps:
        hits_at_k += 1

    # Calculate MRR@K
    try:
        rank = retrieved_diagnosis_steps.index(true_diagnosis_step) + 1
        reciprocal_ranks.append(1 / rank)
    except ValueError:
        # True diagnosis step not found in top-k, reciprocal rank is 0 for this query
        reciprocal_ranks.append(0)

    total_queries += 1

top_k_recall = hits_at_k / total_queries if total_queries > 0 else 0
mrr_at_k = np.mean(reciprocal_ranks) if reciprocal_ranks else 0

print(f"\nTest Set Top-{top_k} Recall: {top_k_recall:.4f}")
print(f"Test Set MRR@{top_k}: {mrr_at_k:.4f}")

"""# `model_2`: SciBERT (base model)

## Initialize Base SciBERT Embedding Model

### Subtask:
Load the pre-trained SciBERT model ('allenai/scibert_scivocab_uncased') using `transformers.AutoModel` and its tokenizer. Then, configure it as a `SentenceTransformer` model with a pooling layer, ensuring no Houslby adapter is used.

## Initialize Base SciBERT Embedding Model

### Subtask:
Load the pre-trained SciBERT model ('allenai/scibert_scivocab_uncased') using `transformers.AutoModel` and its tokenizer. Then, configure it as a `SentenceTransformer` model with a pooling layer, ensuring no Houslby adapter is used.

#### Instructions
1. Import `AutoModel` from `transformers` and `SentenceTransformer`, `models` from `sentence_transformers`.
2. Define the model name as 'allenai/scibert_scivocab_uncased'.
3. Load the tokenizer using `AutoTokenizer.from_pretrained(model_name)`.
4. Load the base SciBERT model using `AutoModel.from_pretrained(model_name)`.
5. Create a `Transformer` module for `SentenceTransformer` using the loaded base SciBERT model and tokenizer. Specify a `max_seq_length` (e.g., 128).
6. Create a `Pooling` module (e.g., mean pooling) using the `word_embedding_dimension` from the `Transformer` module's `auto_model.config.hidden_size`.
7. Combine these modules into a `SentenceTransformer` model, which will be your base embedding model. Name this `base_embedding_model`.

**Reasoning**:
I need to implement the instructions outlined in the previous markdown cell to initialize the base SciBERT embedding model without the Houslby adapter. This involves importing necessary libraries, loading the pre-trained model and tokenizer, and then configuring them into a `SentenceTransformer` model.
"""

from transformers import AutoModel, AutoTokenizer
from sentence_transformers import SentenceTransformer, models

# 1. Define the model name
model_name = "allenai/scibert_scivocab_uncased"

# 2. Load the tokenizer (This tokenizer will be used for consistency in subsequent steps if needed, but models.Transformer also loads its own)
tokenizer_base = AutoTokenizer.from_pretrained(model_name)

# 3. Load the base SciBERT model (This instance is not directly used by models.Transformer in this setup)
base_scibert_model = AutoModel.from_pretrained(model_name)

# 4. Create a Transformer module for SentenceTransformer
max_seq_length = 128
# Fix: models.Transformer loads the model and tokenizer internally from model_name
word_embedding_model = models.Transformer(model_name, max_seq_length=max_seq_length)

# 5. Create a Pooling module (Mean Pooling)
pooling_model_base = models.Pooling(word_embedding_model.get_word_embedding_dimension(), pooling_mode='mean')

# 6. Combine these modules into a SentenceTransformer model
base_embedding_model = SentenceTransformer(modules=[word_embedding_model, pooling_model_base])

print("Base SciBERT embedding model initialized without Houslby adapter.")

"""## Evaluate Base SciBERT Model Performance

### Subtask:
Generate embeddings for all unique symptoms and diagnosis steps in the `test_data` using the `base_embedding_model`. Calculate the top-5 recall based on these embeddings and report the performance to enable comparison with the adapter model's performance.

**Reasoning**:
Now that the `base_embedding_model` is initialized, I will proceed to generate embeddings for the test data and calculate the top-5 recall to evaluate its performance, following the steps previously used for the adapter model.
"""

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import torch

# Set the model to evaluation mode
base_embedding_model.eval()

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
base_embedding_model.to(device)

print("Generating embeddings for the test set using base SciBERT model...")

# Extract unique symptoms and diagnosis steps from test_data
# These were already prepared in a previous step
# all_test_symptoms = [pair[0] for pair in test_data]
# all_test_diagnosis_steps = [pair[1] for pair in test_data]

# unique_test_diagnosis_steps = list(set(all_test_diagnosis_steps)) # Already defined earlier

# Generate embeddings for all unique diagnosis steps (corpus)
print("Generating embeddings for all unique diagnosis steps in the test set (base model)...")
corpus_embeddings_base = base_embedding_model.encode(
    unique_test_diagnosis_steps,
    batch_size=batch_size,
    show_progress_bar=True,
    convert_to_numpy=True,
    device=device
)

# Generate embeddings for each symptom (query) in the test set and calculate recall and MRR

top_k = 5 # Already defined
hits_at_k_base = 0
reciprocal_ranks_base = []
total_queries_base = 0

print(f"Calculating Top-{top_k} Recall and MRR@{top_k} for base SciBERT model...")
for i, (symptom, true_diagnosis_step) in enumerate(test_data):
    # Generate embedding for the current symptom (query)
    query_embedding_base = base_embedding_model.encode(
        [symptom], # Pass as a list of one string
        batch_size=1, # Process one symptom at a time
        show_progress_bar=False,
        convert_to_numpy=True,
        device=device
    )[0] # Take the first (and only) embedding

    # Calculate cosine similarity with all unique diagnosis step embeddings
    similarities_base = cosine_similarity(query_embedding_base.reshape(1, -1), corpus_embeddings_base)[0]

    # Get the indices of the most similar diagnosis steps in descending order
    ranked_indices_base = np.argsort(similarities_base)[::-1]

    # Calculate Top-K Recall
    top_k_indices_base = ranked_indices_base[:top_k]
    retrieved_diagnosis_steps_base = [unique_test_diagnosis_steps[idx] for idx in top_k_indices_base]
    if true_diagnosis_step in retrieved_diagnosis_steps_base:
        hits_at_k_base += 1

    # Calculate MRR@K
    try:
        rank_base = retrieved_diagnosis_steps_base.index(true_diagnosis_step) + 1
        reciprocal_ranks_base.append(1 / rank_base)
    except ValueError:
        # True diagnosis step not found in top-k, reciprocal rank is 0 for this query
        reciprocal_ranks_base.append(0)

    total_queries_base += 1

top_k_recall_base = hits_at_k_base / total_queries_base if total_queries_base > 0 else 0
mrr_at_k_base = np.mean(reciprocal_ranks_base) if reciprocal_ranks_base else 0

print(f"\nBase SciBERT Model Test Set Top-{top_k} Recall: {top_k_recall_base:.4f}")
print(f"Base SciBERT Model Test Set MRR@{top_k}: {mrr_at_k_base:.4f}")

"""## Report Base Model Performance

### Subtask:
Present the calculated top-5 recall score for the base SciBERT model, comparing it to the adapter model's performance to highlight the impact of the Houslby adapter.

## Report Base Model Performance

### Subtask:
Present the calculated top-5 recall score for the base SciBERT model, comparing it to the adapter model's performance to highlight the impact of the Houslby adapter.

### Comparison of Model Performance:

The **Adapter Model (SciBERT with Houslby Adapter)** achieved a **Top-5 Recall of 0.2750** on the test set.

The **Base SciBERT Model (without any adapter)** achieved a **Top-5 Recall of 0.2250** on the test set.

### Analysis of Houslby Adapter Impact:

Comparing the two models, the SciBERT model fine-tuned with the Houslby adapter showed a **0.05 (or 5%) improvement** in Top-5 Recall (0.2750 vs. 0.2250) compared to the base SciBERT model that was not fine-tuned with the adapter. This indicates that the Houslby adapter successfully contributed to adapting the SciBERT model to the specific domain of automotive diagnostics, leading to better retrieval performance for symptom-diagnosis pairs.

The improvement, while modest, demonstrates the effectiveness of the adapter method in enhancing domain-specific understanding. The adapter allowed for targeted fine-tuning with significantly fewer trainable parameters, avoiding the computational cost and potential for catastrophic forgetting associated with full fine-tuning. This result suggests that even with a relatively small dataset and limited training, the Houslby adapter can provide a performance uplift over a vanilla pre-trained model for this specific task.

## Final Task

### Subtask:
Summarize the model's performance, focusing on top-5 recall on the test set, and discuss the effectiveness of the Houslby adapter method.

## Summary:

### Q&A
The model's performance on the test set, specifically regarding top-5 recall, is as follows: the SciBERT model with the Houslby adapter achieved a top-5 recall of 0.2750, while the base SciBERT model without any adapter achieved a top-5 recall of 0.2250.

The Houslby adapter method proved effective, leading to a 0.05 (or 5%) improvement in top-5 recall compared to the base SciBERT model. This indicates its success in adapting the SciBERT model to the specific domain of automotive diagnostics and enhancing retrieval performance.

### Data Analysis Key Findings
*   The base SciBERT model (without any adapter) achieved a Top-5 Recall of 0.2250 on the test set.
*   The SciBERT model fine-tuned with the Houslby adapter achieved a Top-5 Recall of 0.2750 on the test set.
*   The Houslby adapter resulted in a 0.05 (or 5%) improvement in Top-5 Recall, demonstrating its positive impact on the model's performance for this specific task.

### Insights or Next Steps
*   The Houslby adapter effectively enhanced the SciBERT model's domain-specific understanding and retrieval performance for symptom-diagnosis pairs, showcasing the efficiency of adapter-based fine-tuning.
*   Future work could explore optimizing adapter parameters or integrating other adapter types to further improve recall and evaluate performance on a larger, more diverse dataset.

# `model_3`: Fine-tuning SciBERT (full fine-tuning)
"""

from sentence_transformers import SentenceTransformer, models

# 1. Define the model name
model_name = "allenai/scibert_scivocab_uncased"

# 2. Create a Transformer module for SentenceTransformer
max_seq_length = 128
word_embedding_model_full_finetune = models.Transformer(model_name, max_seq_length=max_seq_length)

# 3. Mean Pooling
pooling_model_full_finetune = models.Pooling(word_embedding_model_full_finetune.get_word_embedding_dimension(), pooling_mode='mean')

# 4. Combine these modules into a SentenceTransformer model
full_finetune_model = SentenceTransformer(modules=[word_embedding_model_full_finetune, pooling_model_full_finetune])

print("Full SciBERT model initialized for fine-tuning.")

"""## Define Contrastive Loss for Full Model

 MultipleNegativesRankingLoss
"""

from sentence_transformers import losses

# Define the contrastive loss function for the full fine-tuning model
loss_fn_full_finetune = losses.MultipleNegativesRankingLoss(model=full_finetune_model)

print("Contrastive loss function for full fine-tuning model defined.")

"""## Training Loop


"""

import torch
import torch.optim as optim

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
full_finetune_model.to(device)
print(f"Full fine-tune model moved to device: {device}")

# 1. Initialize an optimizer for the full_finetune_model
# All parameters of this model are trainable by default
optimizer_full_finetune = optim.AdamW(full_finetune_model.parameters(), lr=2e-5)

# 2. Define the number of training epochs
num_epochs = 60 # Consistent with adapter model's training duration

# Training loop
for epoch in range(num_epochs):
    print(f"\n--- Full Fine-tune Epoch {epoch+1}/{num_epochs} ---")
    full_finetune_model.train() # Set model to training mode
    total_train_loss_full = 0

    for step, batch in enumerate(train_dataloader):
        optimizer_full_finetune.zero_grad() # Clear gradients

        # Move batch tensors to the appropriate device
        symptom_input_ids = batch['symptom_input_ids'].to(device)
        symptom_attention_mask = batch['symptom_attention_mask'].to(device)
        diagnosis_input_ids = batch['diagnosis_input_ids'].to(device)
        diagnosis_attention_mask = batch['diagnosis_attention_mask'].to(device)

        # Prepare sentence_features for the MultipleNegativesRankingLoss
        sentence_features_symptoms = {'input_ids': symptom_input_ids, 'attention_mask': symptom_attention_mask}
        sentence_features_diagnosis = {'input_ids': diagnosis_input_ids, 'attention_mask': diagnosis_attention_mask}

        # For MultipleNegativesRankingLoss, if input is [query_features, positive_features],
        # and query_i is positive with positive_i, labels should be torch.arange(batch_size)
        labels = torch.arange(len(symptom_input_ids), dtype=torch.long, device=device)

        # Compute loss
        loss_full = loss_fn_full_finetune([sentence_features_symptoms, sentence_features_diagnosis], labels)

        loss_full.backward() # Perform backpropagation
        optimizer_full_finetune.step() # Update model parameters

        total_train_loss_full += loss_full.item()

        if (step + 1) % 10 == 0: # Print loss every 10 steps for progress monitoring
            print(f"  Step {step+1}/{len(train_dataloader)}, Training Loss (Full): {loss_full.item():.4f}")

    avg_train_loss_full = total_train_loss_full / len(train_dataloader)
    print(f"Epoch {epoch+1} Training Loss (Full): {avg_train_loss_full:.4f}")

    # Validation loop
    full_finetune_model.eval() # Set model to evaluation mode
    total_val_loss_full = 0
    with torch.no_grad(): # Disable gradient calculations for validation
        for batch in val_dataloader:
            symptom_input_ids = batch['symptom_input_ids'].to(device)
            symptom_attention_mask = batch['symptom_attention_mask'].to(device)
            diagnosis_input_ids = batch['diagnosis_input_ids'].to(device)
            diagnosis_attention_mask = batch['diagnosis_attention_mask'].to(device)

            sentence_features_symptoms = {'input_ids': symptom_input_ids, 'attention_mask': symptom_attention_mask}
            sentence_features_diagnosis = {'input_ids': diagnosis_input_ids, 'attention_mask': diagnosis_attention_mask}

            labels = torch.arange(len(symptom_input_ids), dtype=torch.long, device=device)

            val_loss_full = loss_fn_full_finetune([sentence_features_symptoms, sentence_features_diagnosis], labels)
            total_val_loss_full += val_loss_full.item()

    avg_val_loss_full = total_val_loss_full / len(val_dataloader)
    print(f"Epoch {epoch+1} Validation Loss (Full): {avg_val_loss_full:.4f}")

# 5. Save the trained full_finetune_model
output_model_path_full = "./fine_tuned_full_scibert_model"
full_finetune_model.save(output_model_path_full)
print(f"\nFull fine-tune model saved to {output_model_path_full}")

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import torch

# Set the model to evaluation mode
full_finetune_model.eval()

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
full_finetune_model.to(device)

print("Generating embeddings for the test set using fully fine-tuned SciBERT model...")

# Generate embeddings for all unique diagnosis steps (corpus)
# unique_test_diagnosis_steps was defined in previous steps
print("Generating embeddings for all unique diagnosis steps in the test set (full fine-tune model)...")
corpus_embeddings_full_finetune = full_finetune_model.encode(
    unique_test_diagnosis_steps,
    batch_size=batch_size,
    show_progress_bar=True,
    convert_to_numpy=True,
    device=device
)

# Generate embeddings for each symptom (query) in the test set and calculate recall and MRR

top_k = 5 # Already defined
hits_at_k_full_finetune = 0
reciprocal_ranks_full_finetune = []
total_queries_full_finetune = 0

print(f"Calculating Top-{top_k} Recall and MRR@{top_k} for fully fine-tuned SciBERT model...")
for i, (symptom, true_diagnosis_step) in enumerate(test_data):
    # Generate embedding for the current symptom (query)
    query_embedding_full_finetune = full_finetune_model.encode(
        [symptom], # Pass as a list of one string
        batch_size=1, # Process one symptom at a time
        show_progress_bar=False,
        convert_to_numpy=True,
        device=device
    )[0] # Take the first (and only) embedding

    # Calculate cosine similarity with all unique diagnosis step embeddings
    similarities_full_finetune = cosine_similarity(query_embedding_full_finetune.reshape(1, -1), corpus_embeddings_full_finetune)[0]

    # Get the indices of the most similar diagnosis steps in descending order
    ranked_indices_full_finetune = np.argsort(similarities_full_finetune)[::-1]

    # Calculate Top-K Recall
    top_k_indices_full_finetune = ranked_indices_full_finetune[:top_k]
    retrieved_diagnosis_steps_full_finetune = [unique_test_diagnosis_steps[idx] for idx in top_k_indices_full_finetune]
    if true_diagnosis_step in retrieved_diagnosis_steps_full_finetune:
        hits_at_k_full_finetune += 1

    # Calculate MRR@K
    try:
        rank_full_finetune = retrieved_diagnosis_steps_full_finetune.index(true_diagnosis_step) + 1
        reciprocal_ranks_full_finetune.append(1 / rank_full_finetune)
    except ValueError:
        # True diagnosis step not found in top-k, reciprocal rank is 0 for this query
        reciprocal_ranks_full_finetune.append(0)

    total_queries_full_finetune += 1

top_k_recall_full_finetune = hits_at_k_full_finetune / total_queries_full_finetune if total_queries_full_finetune > 0 else 0
mrr_at_k_full_finetune = np.mean(reciprocal_ranks_full_finetune) if reciprocal_ranks_full_finetune else 0

print(f"\nFully Fine-tuned SciBERT Model Test Set Top-{top_k} Recall: {top_k_recall_full_finetune:.4f}")
print(f"Fully Fine-tuned SciBERT Model Test Set MRR@{top_k}: {mrr_at_k_full_finetune:.4f}")